[Docker]
buildfile = "/dist/.oawm/Dockerfile"
repository = "r.erwin.land/gnur/booksing"

[Stages]
[Stages.prep]
Image = "golang:1.10-alpine"
Script = "/src/.oawm/prep.sh"

[Stages.build]
Image = "golang:1.10-alpine"
Script = "/src/.oawm/build.sh"
