runtime: go112

main: ./cmd/server

includes:
  - env_vars.yaml

automatic_scaling:
  max_instances: 1

handlers:
  - url: /js/.*
    static_dir: web/dist/js
    secure: always
  - url: /css/.*
    static_dir: web/dist/css
    secure: always
  - url: /fonts/.*
    static_dir: web/dist/fonts
    secure: always
  - url: /img/.*
    static_dir: web/dist/img
    secure: always

  - url: /.*
    script: auto
    secure: always
