steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
      'build',
      '-t', 'gcr.io/$PROJECT_ID/booksing:${BRANCH_NAME}-${SHORT_SHA}',
      '-t', 'gcr.io/$PROJECT_ID/booksing:${BRANCH_NAME}',
      '.' ]
images:
- 'gcr.io/$PROJECT_ID/booksing:${BRANCH_NAME}-${SHORT_SHA}'
- 'gcr.io/$PROJECT_ID/booksing:${BRANCH_NAME}'
